// <auto-generated />
namespace press_agency_asp_webapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class m : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m));
        
        string IMigrationMetadata.Id
        {
            get { return "202105251035312_m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
